# Generated by Django 3.2.6 on 2022-03-17 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('uid', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('address', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('aid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('roomname', models.CharField(max_length=100)),
                ('roomtype', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('pax', models.CharField(max_length=100)),
                ('isAvailable', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=30)),
                ('mop', models.CharField(max_length=30)),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('rid', models.BigAutoField(primary_key=True, serialize=False)),
                ('roomtype', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('email', models.CharField(max_length=50, unique=True)),
                ('day', models.CharField(max_length=100)),
            ],
        ),
    ]
